### ISSUE TITLE
dhizuku support

### ISSUE THREAD

**Issue by Jimmy39** [SanmerApps/PI#32]
Do you plan to add a support for dhizuku? Dhizuku shares DeviceOwner permissions. For unrooted device, dhizuku doesn't need to be reactivated after reboot.

**Comment by SanmerDev** [comment]
No plan

**Comment by SanmerDev** [comment]
[PI-1.2.0.2450007.dev-642-debug.apk.zip](https://github.com/user-attachments/files/19732739/PI-1.2.0.2450007.dev-642-debug.apk.zip)

**Comment by SanmerDev** [comment]
> [PI-1.2.0.2450007.dev-642-debug.apk.zip](https://github.com/user-attachments/files/19732739/PI-1.2.0.2450007.dev-642-debug.apk.zip)

@optimatrix0 can you try this?

**Comment by optimatrix0** [comment]
Yes!, thankyou.

**Comment by SanmerDev** [comment]
> Yes!, thankyou.

Does it work?

**Comment by optimatrix0** [comment]
I tested the app as requested by selecting the "Dizuku" work mode, but it doesn’t even properly request the necessary permission for the app itself. I had to go into the settings and grant it manually. I forced the stop and cleared PI's cache, but it had no effect. It just displays the message: "The service is not running."

Maybe the code needs a refactoring in order to work with the correct device owner permission. But no worries, you don't need to add anything explicitly related to ownership—just make the code run with that permission and obtain it through the API.

I hope you don’t give up. Let’s move forward, because this approach would bring PI much closer to a rooted installation. Plus, it would solve several issues with newer versions of Android, since apps installed as device owner are considered trustworthy.

**Comment by SanmerDev** [comment]
[PI-1.2.0.2450007.dev-642-debug.apk.zip](https://github.com/user-attachments/files/19734623/PI-1.2.0.2450007.dev-642-debug.apk.zip)

It should work fine now. I forgot to initialize it last time.

**Comment by SanmerDev** [comment]
> [PI-1.2.0.2450007.dev-642-debug.apk.zip](https://github.com/user-attachments/files/19734623/PI-1.2.0.2450007.dev-642-debug.apk.zip)
> 
> It should work fine now. I forgot to initialize it last time.

@optimatrix0 try this?

**Comment by optimatrix0** [comment]
I tested both the first and second versions you sent, but it seems that the app does not have the declared permission for Dizuku, which appears to be an illegal behavior on Android. I'm not a developer or anything, and on top of that, I'm visually impaired, which might affect my analysis and explanations.

But basically, what happened was this:

1. Open the app after installing it.


2. Select the work mode.


3. Click on "Grant", and then the app crashes abruptly.



I’m not sure if this is relevant, but the only special permission that appears on the app’s settings page is the Shizuku permission—Dizuku should definitely appear there as well.

That said, you’re already on the right track, because the app does request the permission for the API correctly. However, Android doesn’t seem to recognize the permission, which might be causing the issue.

Please keep in mind that I don’t have any special development skills, but I’m reporting everything as sincerely as possible. I tested all the versions you sent me, including the most recent one—the one you mentioned you had forgotten to initialize.

**Comment by SanmerDev** [comment]
@optimatrix0 Thanks for your help, there might be some errors that need logs, so I'll test it myself

**Comment by SanmerDev** [comment]
I can't activate Dhizuku on my device, so I have to put this issue aside for now.

**Comment by optimatrix0** [comment]
I’d also like to thank the author of this problem for giving me the opportunity to help.

**Comment by optimatrix0** [comment]
Disable all account-related apps using ADB; that way, you'll be able to remove all accounts from the device and run the activation command afterward. After that, you can re-enable all the apps normally, and you won't lose any important data. You can trust me on this.

**Comment by optimatrix0** [comment]
---

Hello! I'm ChatGPT, and I'm writing this message on behalf of a user who asked me to help compose it. The user is actively testing and providing detailed feedback on your open-source project, PI (Package Installer). They’re visually impaired and not a developer, but they’ve done thorough testing and are contributing with sincere and insightful bug reports.


---

Context & Testing Notes:

The user has tested all recent versions of the app, including the one where you mentioned you had forgotten to initialize something. In these tests:

They selected Dhizuku as the working mode.

The app prompted the user to grant access to the API.

However, after clicking to grant access, the app crashes or closes abruptly.


From further analysis, this seems to be due to a bug in the current implementation or how the app integrates with the Dhizuku API. Other apps using this API do not present the same issue, indicating it’s not a system-level limitation but something that likely needs to be fixed within the app.


---

Suggestions for Improving Dhizuku Integration:

1. Ensure proper initialization and access to the Dhizuku API after permission is granted.


2. Add better error handling when the API service is unavailable or not responding. Clear user feedback or logs could help in troubleshooting.


3. Follow the official guidelines for checking service status and interacting with the API to guarantee compatibility and reliability.


4. Make sure the app can interact with the Dhizuku API successfully in different Android environments, including those with advanced privilege setups.




---

Helpful Resources:

Dhizuku API Documentation: https://github.com/iamr0s/Dhizuku-API

Dhizuku Project Repository: https://github.com/iamr0s/Dhizuku


The user is very thankful for your work and hopes to keep contributing with feedback. Keep going — this project has amazing potential!

**Comment by yavko** [comment]
Here are some logs if it helps
```
type: crash
osVersion: google/husky/husky:15/BP1A.250405.007.B1/2025041100:user/release-keys
flags: dev options enabled
package: dev.sanmer.pi:642, targetSdk 35
process: dev.sanmer.pi
processUptime: 460 + 130 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to create service dev.sanmer.pi.service.InstallService: java.lang.IllegalStateException: Pending
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5170)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2556)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8973)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
Caused by: java.lang.IllegalStateException: Pending
	at dev.sanmer.pi.repository.ServiceRepository.unsafe(ServiceRepository.kt:64)
	at dev.sanmer.pi.repository.ServiceRepository.getPackageInstaller(ServiceRepository.kt:70)
	at dev.sanmer.pi.service.InstallService.pi_delegate$lambda$3(InstallService.kt:60)
	at dev.sanmer.pi.service.InstallService.$r8$lambda$3J9IpnoYmfRJgkqyRgQGDp9eogs(Unknown Source:0)
	at dev.sanmer.pi.service.InstallService$$ExternalSyntheticLambda3.invoke(D8$$SyntheticClass:0)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83)
	at dev.sanmer.pi.service.InstallService.getPi(InstallService.kt:60)
	at dev.sanmer.pi.service.InstallService.onCreate(InstallService.kt:100)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5157)
	... 9 more

```

**Comment by SanmerDev** [comment]
At present, Dhizuku's performance does not meet my expectations.

**Comment by ManiaciaChao** [comment]
> At present, Dhizuku's performance does not meet my expectations.

Hey, could you clarify what you meant by "performance"? Was it running slowly, or was it failing to complete the task (e.g., due to insufficient permissions)?
