### ISSUE TITLE
The app crashes when trying to access the sessions tab before the app list is loaded

### ISSUE THREAD

**Issue by eyalm2000** [SanmerApps/PI#77]
https://github.com/SanmerApps/PI/assets/141010573/0f9ba32b-fa40-4002-8a56-fe29faf19ca1

**Comment by SanmerDev** [comment]
I already knew it.
> Please provide logs when you report bugs, because a video is not helpful at all in finding the problem.

**Comment by eyalm2000** [comment]
FATAL EXCEPTION: main
Process: dev.sanmer.pi, PID: 27133
java.lang.IllegalStateException: IServiceManager haven't been received
	at dev.sanmer.pi.hS.b(Unknown Source:13)
	at dev.sanmer.pi.hS.f(Unknown Source:0)
	at dev.sanmer.pi.BK.b(Unknown Source:4)
	at dev.sanmer.pi.x6.d(Unknown Source:12)
	at dev.sanmer.pi.x6.e(Unknown Source:0)
	at dev.sanmer.pi.dR.q(Unknown Source:64)
	at dev.sanmer.pi.k8.r(Unknown Source:7)
	at dev.sanmer.pi.uj.run(Unknown Source:114)
	at dev.sanmer.pi.P0.run(Unknown Source:47)
	at dev.sanmer.pi.qW.run(Unknown Source:2)
	at dev.sanmer.pi.Sf.run(Unknown Source:95)
	Suppressed: dev.sanmer.pi.Wi: [gi{Cancelling}@de9315d, Dispatchers.Main.immediate]
